import { test } from '../customFixtures/salesForceFixture';
import { JdePrintPickSlipPage } from '../pages/jdePrintPickSlipPage';

test('Verify Print Pick Slip process', async ({ page, context }) => {
    const jdePrintPickSlipPage = new JdePrintPickSlipPage(page, context);

    await jdePrintPickSlipPage.navigateToUrl('https://mirajde-dvtrweb.birlasoft.com/jde/E1Menu.maf?');
    await jdePrintPickSlipPage.typeUsername('TESTT02');
    await jdePrintPickSlipPage.typePassword('Welcome123');
    await jdePrintPickSlipPage.clickSignIn();
    await jdePrintPickSlipPage.verifyPageTitle('JD Edwards');
    await jdePrintPickSlipPage.clickNavigator();
    await jdePrintPickSlipPage.clickEnterpriseOneMenus();
    await jdePrintPickSlipPage.clickOrderManagement();
    await jdePrintPickSlipPage.clickSalesOrderManagement();
    await jdePrintPickSlipPage.clickDailySalesOrderManagementProcessing();
    await jdePrintPickSlipPage.clickSalesOrderProcessing();
    await jdePrintPickSlipPage.clickPrintPickSlips();
    await jdePrintPickSlipPage.selectCheckboxInRowDM001();
    await jdePrintPickSlipPage.clickSelectIcon();
    await jdePrintPickSlipPage.verifyPageTitle('Version Prompting');
    await jdePrintPickSlipPage.selectDataSelectionCheckbox();
    await jdePrintPickSlipPage.clickSubmitIcon();
    await jdePrintPickSlipPage.selectLeftOperandOption('Document (Order No, Invoice, etc.) (F4201) (DOCO) [BC]');
    await jdePrintPickSlipPage.selectComparisonOption('is equal to');
    await jdePrintPickSlipPage.selectRightOperandOption('Literal');
    await jdePrintPickSlipPage.verifyTextVisible('Select Literal Value');
    await jdePrintPickSlipPage.enterLiteralValue('12195');
    await jdePrintPickSlipPage.clickOkIconInFrame();
    await jdePrintPickSlipPage.verifyTextVisible('Data Selection');
    await jdePrintPickSlipPage.clickOkIconInFrame();
    await jdePrintPickSlipPage.verifyTextVisible('Processing Options');
    await jdePrintPickSlipPage.clickOkIconInFrame();
    await jdePrintPickSlipPage.verifyTextVisible('Printer Selection');
    await jdePrintPickSlipPage.clickFinalOkIconInFrame();
    await jdePrintPickSlipPage.verifyTextVisible('Work With Batch Versions-Available Versions');
    await jdePrintPickSlipPage.clickViewJobStatus();
    await jdePrintPickSlipPage.clickFirstViewOutputIcon();
    await jdePrintPickSlipPage.verifyOrderNumberInPdf('12195');
    await jdePrintPickSlipPage.clickNavigator();
    await jdePrintPickSlipPage.clickEnterpriseOneMenus();
    await jdePrintPickSlipPage.clickOrderManagement();
    await jdePrintPickSlipPage.clickSalesOrderManagement();
    await jdePrintPickSlipPage.clickDailySalesOrderManagementProcessing();
    await jdePrintPickSlipPage.clickSalesOrderProcessing();
    await jdePrintPickSlipPage.clickSalesOrderDetail();
    await jdePrintPickSlipPage.enterOrderNumber('12195');
    await jdePrintPickSlipPage.clickFindIcon();
    await jdePrintPickSlipPage.verifyCustomerPO('jde');
});
