import { test } from '../customFixtures/salesForceFixture';
import { URLConstants } from '../constants/urlConstants';

test('Verify Print Invoices process', async ({ JdePrintInvoices }) => {
    await JdePrintInvoices.navigateToUrl(URLConstants.adminURL);
    await JdePrintInvoices.typeUsername('TESTT02');
    await JdePrintInvoices.typePassword('Welcome123');
    await JdePrintInvoices.clickSignIn();
    await JdePrintInvoices.verifyPageTitle('JD Edwards');
    await JdePrintInvoices.clickNavigator();
    await JdePrintInvoices.clickEnterpriseOneMenus();
    await JdePrintInvoices.clickOrderManagement();
    await JdePrintInvoices.clickSalesOrderManagement();
    await JdePrintInvoices.clickDailySalesOrderManagementProcessing();
    await JdePrintInvoices.clickSalesOrderProcessing();
    await JdePrintInvoices.clickPrintInvoices();
    await JdePrintInvoices.selectCheckboxInRowIKOTEST();
    await JdePrintInvoices.clickSelectIcon();
    await JdePrintInvoices.verifyPageTitle('Version Prompting');
    await JdePrintInvoices.selectDataSelectionCheckbox();
    await JdePrintInvoices.clickSubmitIcon();
    await JdePrintInvoices.selectLeftOperandOption('Document (Order No, Invoice, etc.) (F4211) (DOCO) [BC]');
    await JdePrintInvoices.selectComparisonOption('is equal to');
    await JdePrintInvoices.selectRightOperandOption('Literal');
    await JdePrintInvoices.verifyTextVisible('Select Literal Value');
    await JdePrintInvoices.enterLiteralValue('12185');
    await JdePrintInvoices.clickOkIconInFrame();
    await JdePrintInvoices.verifyTextVisible('Data Selection');
    await JdePrintInvoices.clickOkIconInFrame();
    await JdePrintInvoices.verifyTextVisible('Processing Options');
    await JdePrintInvoices.clickOkIconInFrame();
    await JdePrintInvoices.verifyTextVisible('Printer Selection');
    await JdePrintInvoices.clickFinalOkIconInFrame();
    await JdePrintInvoices.verifyTextVisible('Work With Batch Versions-Available Versions');
    await JdePrintInvoices.clickViewJobStatus();
    await JdePrintInvoices.clickFirstViewOutputIcon();
    await JdePrintInvoices.verifyOrderNumberInPdf('12185');
    await JdePrintInvoices.verifyItemNumberInPdfRow('Touring Bike, Red', '220');
    await JdePrintInvoices.clickNavigator();
    await JdePrintInvoices.clickEnterpriseOneMenus();
    await JdePrintInvoices.clickOrderManagement();
    await JdePrintInvoices.clickSalesOrderManagement();
    await JdePrintInvoices.clickDailySalesOrderManagementProcessing();
    await JdePrintInvoices.clickSalesOrderProcessing();
    await JdePrintInvoices.clickSalesOrderDetail();
    await JdePrintInvoices.enterOrderNumber('12185');
    await JdePrintInvoices.clickFindIcon();
    await JdePrintInvoices.verifyOrderNumber('12185');
    await JdePrintInvoices.verifyCustomerPO('jde-01');
});