export const selectors = {
    username: '#username',
    password: '#password',
    loginBtn: 'Login',
    applauncherIcon: '.slds-icon-waffle',
    homeLabel: "//h1//span[text()='Home']",

    home: {
        appLauncherIcon: '.slds-icon-waffle',
        viewAllBtn: "//button[normalize-space()='View All']",
        appSearchInput: "//input[@placeholder='Search apps or items...']",
        selectApp: (appName: string) => `//mark[normalize-space()='${appName}']`,
    },

    accounts: {
        newBtn: "//div[@title='New']",
        accountNameInput: "//input[@name='Name']",
        phoneInput: "//input[@name='Phone']",
        saveBtn: "//button[@name='SaveEdit']",
        verificationText: "//slot//lightning-formatted-text[@slot='primaryField']",
        searchInput: "//input[@placeholder='Search this list...']",
        accountRecordLink: (accountName: string) => `//a[@title='${accountName}']`,
        editBtn: "button[name='Edit']",
        deleteBtn: "button[name='Delete']",
        confirmDeleteBtn: "//button[.//span[normalize-space()='Delete']]",
        toastMessage: "//span[contains(@class,'toastMessage')]",
    },
    jdeSummaryAvailability: {
    usernameInput: '#User',
    passwordInput: '#Password',
    signInButton: '#menuAndFastPathContainer',
    navigatorButton: 'button:has-text("Navigator")',
    enterpriseOneMenusLink: 'text=EnterpriseOne Menus',
    logisticsManagementLink: 'text=Logistics Management',
    inventoryManagementLink: 'text=Inventory Management',
    dailyProcessingLink: 'text=Daily Processing',
    inventoryInquiriesLink: 'text=Inventory Inquiries',
    summaryAvailabilityLink: 'text=Application: P41202, Form: W41202A, Version: ZJDE0001',
    frameLocator: '#e1menuAppIframe',
    itemNumberInput: '[name="0_17"]',
    branchPlantInput: '#C0_7',
    displayOptionsDropdown: 'text=function jdeTabRegisterFunction0_281(){\nvar jdeTabPages0_281',
    displayOptionItem: (option: string) => `option:has-text("${option}")`,
    findIcon: '#hc_Find',
    onHandCell: '#jdeGridBack0_319 td[colindex="4"]'
  },
};
